In [121]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [122]:
data = pd.read_csv('/kaggle/input/digit-recognizer/train.csv')

In [123]:
data.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [124]:
data = np.array(data)
m, n = data.shape
np.random.shuffle(data)

data_dev = data[0:2000].T
Y_dev = data_dev[0]
X_dev = data_dev[1:n]
X_dev = X_dev / 255.

data_train = data[2000:m].T
Y_train = data_train[0]
X_train = data_train[1:n]
X_train = X_train / 255.
_,m_train = X_train.shape

In [125]:
def init_params():
    W1 = np.random.rand(10, 784) - 0.5
    b1 = np.random.rand(10, 1) - 0.5
    W2 = np.random.rand(10, 10) - 0.5
    b2 = np.random.rand(10, 1) - 0.5
    return W1, b1, W2, b2

def ReLU(Z):
    return np.maximum(0, Z)

def softmax(Z):
    return np.exp(Z) / sum(np.exp(Z))

def forward_prop(W1, b1, W2, b2, X):
    Z1 = W1.dot(X) + b1
    A1 = ReLU(Z1)
    Z2 = W2.dot(A1) + b2
    A2 = softmax(Z2)
    return Z1, A1, Z2, A2

def one_hot(Y):
    one_hot_Y = np.zeros((Y.size, Y.max() + 1))
    one_hot_Y[np.arange(Y.size), Y] = 1
    one_hot_Y = one_hot_Y.T
    return one_hot_Y

def deriv_ReLU(Z):
    return Z > 0

def back_prop(Z1, A1, Z2, A2, W1, W2, X, Y):
    m = Y.size
    one_hot_Y = one_hot(Y)
    dZ2 = A2 - one_hot_Y
    dW2 = 1 / m * dZ2.dot(A1.T)
    db2 = 1 / m * np.sum(dZ2)
    dZ1 = W2.T.dot(dZ2) * deriv_ReLU(Z1)
    dW1 = 1 / m * dZ1.dot(X.T)
    db1 = 1 / m * np.sum(dZ1)
    return dW1, db1, dW2, db2

def update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha):
    W1 = W1 - alpha * dW1
    b1 = b1 - alpha * db1
    W2 = W2 - alpha * dW2
    b2 = b2 - alpha * db2
    return W1, b1, W2, b2

In [126]:
def get_predictions(A2):
    return np.argmax(A2, 0)

def get_accuracy(predictions, Y):
    print(predictions, Y)
    return np.sum(predictions == Y) / Y.size

In [130]:
def gradient_descent(X, Y, iterations, alpha):
    W1, b1, W2, b2 = init_params()
    for i in range(iterations):
        if (alpha > 0.10):
            alpha = alpha / (1 + 0.01 * i)
        Z1, A1, Z2, A2 = forward_prop(W1, b1, W2, b2, X)
        dW1, db1, dW2, db2 = back_prop(Z1, A1, Z2, A2, W1, W2, X, Y)
        W1, b1, W2, b2 = update_params(W1, b1, W2, b2, dW1, db1, dW2, db2, alpha)
        if (i % 10 == 0):
            print("Iteration: ", i)
            predictions = get_predictions(A2)
            print("Accuracy: ", get_accuracy(predictions, Y))
    return W1, b1, W2, b2

In [131]:
W1, b1, W2, b2 = gradient_descent(X_train, Y_train, 500, 0.15)

Iteration:  0
[0 7 8 ... 8 4 8] [2 7 6 ... 6 4 2]
Accuracy:  0.131975
Iteration:  10
[0 7 8 ... 8 4 8] [2 7 6 ... 6 4 2]
Accuracy:  0.213725
Iteration:  20
[0 7 0 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.29035
Iteration:  30
[0 7 6 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.329175
Iteration:  40
[0 7 6 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.369375
Iteration:  50
[0 7 6 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.4177
Iteration:  60
[0 7 2 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.46275
Iteration:  70
[0 7 2 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.50465
Iteration:  80
[2 7 2 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.54255
Iteration:  90
[2 7 2 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.57945
Iteration:  100
[2 7 2 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.61515
Iteration:  110
[2 7 2 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.64495
Iteration:  120
[2 7 2 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.67025
Iteration:  130
[2 7 2 ... 6 4 6] [2 7 6 ... 6 4 2]
Accuracy:  0.68985
Iteration:  14